### PR TITLE
Update quic-go to support go-1.21.0

### PR DESCRIPTION
**Pull request by syphyr**
Update to quic-go v0.37.4
Fixes go-1.21.0

### CODE REVIEW

**Comment by jedisct1** [comment]
Updated thanks!

**Comment by syphyr** [comment]
I noticed that the PR that was merged excluded this file:
[vendor/github.com/quic-go/qtls-go1-20/tls.test](https://github.com/DNSCrypt/dnscrypt-proxy/pull/2453/files#diff-cc1c363c1859f3c9e4dc1f4b7bf230931483c917b5c2af7e73f67f2711525206)

**Comment by syphyr** [comment]
After rebasing master branch with this, if I type "go mod vendor" the mentioned file above is added back again.

**Comment by jedisct1** [comment]
Did you type `go mod tidy` afterwards?

**Comment by syphyr** [comment]
Yes

**Comment by syphyr** [comment]
This new vendor file is added by latest version of quic-go

**Comment by syphyr** [comment]
Maybe this new vendor file from quic-go has not been noticed because the *.test extension is being ignored by git.

**Pull request closed without merging**
