### PR TITLE
add allowed ips plugin

### PR DESCRIPTION
**Pull request by ianbashford**
RE: issue #1488 
First cut at an Allowed IP plugin - I wasn't sure what you thought of the suggestion in that issue but it didn't seem unreasonable.  Of course if you have issues with the concept let me know... 

Notes:  I've begun to adopt 'allow' in the code. I've not refactored it all in order to keep the size of the PR reasonable, but this should be a step towards aligning the code with the external facing terminology.

WIP - tested with same IP in both blocked-ips.txt and allowed-ips.txt and shown it to provide the functionality.  I've not tested the log file or formats yet... thought I'd garner some feedback and see how it was received.

### CODE REVIEW

**Comment by ianbashford** [comment]
Quick note about the implementation here
THe priorities are as follows:
AllowedName > BlockedName > AllowedIP > BlockedIp

The change here of course is just the insertion of AllowedIP
Otherwise I think the MR is in good shape now

**Comment by jedisct1** [comment]
Thanks a lot Ian!

Is the `ltsv` log format actually unsupported? In the plugin code, it looks like it is handled.

**Comment by ianbashford** [comment]
It should support `ltsv`  - I must be missing something as I can't see the block of code where I exclude it.  
`config.go`  looks OK doesn't it?  If you don't mind giving me a pointer, I'll correct whatever is misleading... 

<edit>  seems to output `ltsv` OK

**Comment by jedisct1** [comment]
NVM, I was confused by the code in `config.go`.

**Comment by ianbashford** [comment]
Oh -- I just had to look at that a few times....   I ended up running it to convince myself.

**Comment by ianbashford** [comment]
Hi -- have you had a chance to take a look at this?
I you're OK with the concept I can rebase it against master -- if you're not so keen on the concept it's NP either... happy to discuss as well of course.
Any thoughts / comments welcomed.

**Comment by jedisct1** [comment]
If it can be useful, yes, totally!

If you could rebase it, that would be wonderful. I'll merge it right after.

**Comment by ianbashford** [comment]
I'm not having fun with the rebase...   I'll resubmit a new PR

**Pull request closed without merging**
