### PR TITLE
Add DOH certificate generation commands into the example config.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you!

**Comment by syphyr** [comment]
Is there a reason why the commands to generate localhost.pem changed from what the wiki currently says?

openssl req -x509 -nodes -newkey rsa:2048 -days 5000 -sha256 -keyout \
  localhost.pem -out localhost.pem

**Comment by KOLANICH** [comment]
RSA is a heavy asymmetric crypto method; since this crypto is not really used for security (we use a resolver under our control), I have changed it to a lightweight ECC suitable even for embedded devices (it is used in OpenWRT by default, if TLS is enabled in Web GUI). Though this curve is not in the [list of safe curves](https://safecurves.cr.yp.to/), again, we use encryption in that case only to workaround the flaws in Firefox that seem will never be fixed.

**Comment by jedisct1** [comment]
RSA verification is faster than ECC.

And according to the recent activity on the relevant ticket, looks like Firefox will eventually fix the ECH issue.

**Comment by KOLANICH** [comment]
Thank you for the info.

**Pull request merged**
