### PR TITLE
Add sources in [domains-blocklist.conf]

### PR DESCRIPTION
**Pull request by d3cim**
_NextDNS CNAME cloaking list_ is already contained in [your big source](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md?plain=1#L47). No reason to merge it two times.

### CODE REVIEW

**Comment by d3cim** [comment]
- _Peter Lowe's Ad and tracking server list_ [is here](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md?plain=1#L5)

- _BarbBlock list (spurious and invalid DMCA takedowns)_ [is here](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md?plain=1#L10)

**Comment by d3cim** [comment]
Frogeye 1st-party isn't contained instead and it is fine. In these days I try to enhance your list in according to [my additions](https://github.com/quindecim/block#sources).

**Comment by jedisct1** [comment]
Can you clarify what "your big source" is?

And there's nothing wrong with having duplicates, as the script will remove them.

**Comment by d3cim** [comment]
> Can you clarify what "your big source" is?

Sure, I am referring to [notracking blocklist](https://github.com/notracking/hosts-blocklists). Is a blocklist containing [more than 100 blocklists](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md), including the ones I listed above ([NextDNS CNAME](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md?plain=1#L47), [Peter Lowe's Ad and tracking](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md?plain=1#L5) and [BarbBlock list](https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md?plain=1#L10)).

> And there's nothing wrong with having duplicates, as the script will remove them.

True, but it doesn't make sense because in this case the script is removing the entire lists you are unnecessarily merging.
It makes more sense spent resources in adding new blocklists, as in the case of Frogeye, which is not contained in any of the 113 notracking's lists.

You can merge instead:

| Source | Maintainer(s) | Description | Home Page | RAW Source | License |
|--------|:-------------:|-------------|:---------:|:----------:|:-------:|
anudeepND: adservers | anudeepND (Anudeep) | Block advertising, trackers, malwares and other unsafe domains. | [LINK](https://github.com/anudeepND/blacklist) | [RAW](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt) | [MIT](https://github.com/anudeepND/blacklist/blob/master/LICENSE) |
Developer Dan: Ads & Tracking | Daniel (lightswitch05) | Block advertising, trackers, malwares and other unsafe domains. | [LINK](https://github.com/lightswitch05/hosts) | [RAW](https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt) | [Apache-2.0](https://github.com/lightswitch05/hosts/blob/master/LICENSE) |

None of these lists contain itself in the others, so now it makes sense to make the script work to remove duplicates and add new ones, reinforcing the blocking ability.

This is my approach and I don't want to influence your decision.. I can still see positive aspects such as continuing to merging them even if one day notracking decides to remove them from its sources.

Feel free to close this PR at anytime.

**Comment by jedisct1** [comment]
Adding them still has the advantage of having more up-to-date lists: entries from the lists are merged with their content at the time the script is run, rather than when the notracking list eventually fetches and updates their own copy.

The notrack list also may bring licensing issues, since some of the lists is contains a copy of don't have an explicit license or have a license that doesn't allow them to be used unconditionally (ex: in a commercial environment).

Having both notrack and some of the list it depends on being enabled makes it easier to comment out notrack and keep fetching other ones directly. 

So I'd rather keep status quo.

Anudeep and Ligthswitch lists look good! Even more if they don't appear to be redundant. So adding them is a good idea!

**Comment by d3cim** [comment]
Ready to be merged.

**Comment by jedisct1** [comment]
Are these safe to be enabled by default without risking having too many false positives?

**Comment by d3cim** [comment]
Yes. We have been testing these blocklists as part of a [large blocklist](https://github.com/quindecim/block#inclusions) for months now and we have not found any issues in them.

**Pull request merged**
