### PR TITLE
make sure app main goroutine quits, before stopping

### PR DESCRIPTION
**Pull request by vbauerster**
I've noticed that `*App.wg` never waited in main.go, so this PR fixes this.

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi Vlad,

And thanks for your contribution!

I'd like to hold off for a bit before making internal changes, so that people can test the current beta, and version 2.0.29 (final, non beta) can be released soon.
So, for a couple days, only important bugs found in the beta should go in. Other changes will be made right after the final version is released.

Your patch looks good, although it probably needs a bit of testing on different platforms including Windows.

**Comment by vbauerster** [comment]
My setup is `unbound` as front, backed by `dnscrypt-proxy` via systemd sockets. After some usage, I noticed that if I restart `dnscrypt-proxy` via `systemctl`, `unbound` gives empty results after a while, so I have to restart the whole system. Some code review revealed that connections were not closed properly (goroutine that defers Close() never quits). So I think this is the reason why `unbound` stops to respond if `dnscrypt-proxy` restarted.

Second commit tries to fix this, i.e. make sure all conn are closed on stop signal. I've tested with this patch and `unbound` continues to respond after `dnscrypt-proxy` have been restarted.

**Comment by jedisct1** [comment]
Alright. It seems to work fine on Windows and macOS, so let's merge this.

Thanks again, Vlad!

**Comment by jedisct1** [comment]
The downside of that change is that we can't quit any more while the servers list is being built. Which can take some time with the default settings (all resolvers).

**Comment by vbauerster** [comment]
Ok, I think I got what you mean. I'll review this one more time.

**Pull request merged**
