### PR TITLE
Optimize stopping CaptivePortalHandler

### PR DESCRIPTION
**Pull request by lifenjoiner**
Optimize https://github.com/DNSCrypt/dnscrypt-proxy/pull/2136/commits/f415525e176fbc88735d37570ef919e8bbd8b592.

### CODE REVIEW

**Comment by syphyr** [comment]
This commit is causing dnscrypt-proxy to crash upon bootup on arm64 (on my T813 running cm-14.1). I could not find anything in the logs regarding the crash, but it happens on every boot.  I have reverted this commit and everything is working again.

**Comment by syphyr** [comment]
I also did not see any problems with this commit when using amd64, only when using arm64.  It looks like this crash on boot is only happening on specific arches.

**Comment by jedisct1** [comment]
Or it's some kind of race condition.

**Comment by jedisct1** [comment]
What does the crash actually looks like? Do you have a stack trace?

**Comment by syphyr** [comment]
I'm running dnscrypt-proxy as a service on android and logcat does not show anything about the crash.  I can just see that dnscrypt-proxy process has stopped after booting up.

**Comment by jedisct1** [comment]
If there a way you could run it directly from a shell?

**Comment by lifenjoiner** [comment]
This is really unexpected.

I tested it on Android 7.0 with Qualcomm Snapdragon 820. Both [ARM64](https://github.com/lifenjoiner/dnscrypt-proxy/releases/download/TestAndroid-1/dnscrypt-proxy-android_arm64-TestAndroid-1.zip) and [ARM](https://github.com/lifenjoiner/dnscrypt-proxy/releases/download/TestAndroid-1/dnscrypt-proxy-android_arm-TestAndroid-1.zip) versions work.

Here is what I did on Windows:
1. Download the above zip files, and unzip them.
2. Rename `example-dnscrypt-proxy.toml` to `dnscrypt-proxy.toml`, and modified the config with:
    2.1. `listen_addresses = ['127.0.0.1:50053']`
    2.2. `file = '/dev/stdout'` for `[query_log]`;
3. Run commands:
    ```
    adb push D:\DNS\dnscrypt-proxy\test\android\android-arm64\dnscrypt-proxy /data/local/tmp/
    adb push D:\DNS\dnscrypt-proxy\test\android\android-arm64\dnscrypt-proxy.toml /data/local/tmp/
    adb shell chmod 755 /data/local/tmp/dnscrypt-proxy
    adb shell /data/local/tmp/dnscrypt-proxy
    ```
    It works.
4. I even push the [doggo](https://github.com/mr-karan/doggo/releases/download/v0.5.4/doggo_0.5.4_linux_arm64.tar.gz) to the device, with a new shell window, then run
    ```adb shell /data/local/tmp/doggo github.com @udp://127.0.0.1:50053```
    and confirmed `dnscrypt-proxy` is servicing well.

**Comment by lifenjoiner** [comment]
I suspect the `close` in the `for` loop of `Stop` in this case ...

I made a [more optimized version](https://github.com/lifenjoiner/dnscrypt-proxy/commit/f205506a98ec5640464ddb56246cc78618303773) with only 1 channel: [download](https://github.com/lifenjoiner/dnscrypt-proxy/releases/download/TestAndroid-2/dnscrypt-proxy-android_arm64-TestAndroid-2.zip). Could you test it? @syphyr

**Comment by lifenjoiner** [comment]
`listen_addresses = ['127.0.0.1:50053', '127.0.0.1:50153', '127.0.0.1:50253']` also works by my test, both versions.

**Comment by syphyr** [comment]
> I suspect the `close` in the `for` loop of `Stop` in this case ...
> 
> I made a [more optimized version](https://github.com/lifenjoiner/dnscrypt-proxy/commit/f205506a98ec5640464ddb56246cc78618303773) with only 1 channel: [download](https://github.com/lifenjoiner/dnscrypt-proxy/releases/download/TestAndroid-2/dnscrypt-proxy-android_arm64-TestAndroid-2.zip). Could you test it? @syphyr

I just tested this and it did not fix the issue, unfortunately.  When I run this from the command line in a shell, this is the output:

```
[2022-07-18 21:57:08] [NOTICE] dnscrypt-proxy 2.1.2
[2022-07-18 21:57:08] [NOTICE] Network connectivity detected
[2022-07-18 21:57:08] [FATAL] listen udp 127.0.0.1:50053: bind: address already in use
```

I do not see any other errors, it just never starts.

When I run dnscrypt from shell with "Optimize stopping CaptivePortalHandler" reverted, it works as expected.

**Comment by syphyr** [comment]
If it helps for testing, this is the config file i'm using: https://github.com/syphyr/dnscrypt_proxy_prebuilt/blob/master/etc/dnscrypt-proxy/dnscrypt-proxy-tor.toml  (but I also added the recommended edits you mentioned above to change the listen address and logging to file to /dev/stdout)

**Comment by syphyr** [comment]
Maybe this issue is triggered by some of the other differences in my config

**Comment by lifenjoiner** [comment]
> [2022-07-18 21:57:08] [NOTICE] Network connectivity detected
> [2022-07-18 21:57:08] [FATAL] listen udp 127.0.0.1:50053: bind: address already in use

Ooh, I got it. `Stop` returns too quickly causes port rebinding issue. `map_file` should be enabled to reproduce the issue.

@syphyr 
[Try this one](https://github.com/lifenjoiner/dnscrypt-proxy/releases/tag/TestAndroid-3).

**Comment by syphyr** [comment]
> > [2022-07-18 21:57:08] [NOTICE] Network connectivity detected
> > [2022-07-18 21:57:08] [FATAL] listen udp 127.0.0.1:50053: bind: address already in use
> 
> Ooh, I got it. `Stop` returns too quickly causes port rebinding issue. `map_file` should be enabled to reproduce the issue.
> 
> @syphyr [Try this one](https://github.com/lifenjoiner/dnscrypt-proxy/releases/tag/TestAndroid-3).

Thank you! This fixes the issue.  Great work.

**Comment by jedisct1** [comment]
Wow, great work @lifenjoiner and thank you for reporting this @syphyr !

**Pull request merged**
