### PR TITLE
Upgrade request to https

### PR DESCRIPTION
**Pull request by arch-btw**
Upgrade request to https

### CODE REVIEW

**Comment by jedisct1** [comment]
Unfortunately this is intentional. Their TLS configuration is a little bit atypical.

TLS 1.2 connections are not supported, and while we may assume that Python is going to use TLS 1.3 on every platform, this is likely not the case. Even connecting to that website from macOS with the `curl` command is currently impossible.

**Comment by arch-btw** [comment]
Hey, thank you for your reply and for your hard work.

That's really unfortunate that they have an atypical TLS configuration.

In that case it's better not to merge. 

Thank you again!

**Comment by arch-btw** [comment]
I just noticed that the hosts file is depreciated and no longer updated:



On their website: http://www.sysctl.org/cameleon/

Maybe a solution is to use the archived version on archive.org?

https://web.archive.org/web/20201112015556if_/http://sysctl.org/cameleon/hosts

If you rather not I totally understand :-)

**Comment by jedisct1** [comment]
Whoops, thanks for the heads up!

If it is not maintained any more, it's probably better to remove it. Legacy lists tend not to be very useful and have a lot of false positives.

**Pull request closed without merging**
