### PR TITLE
Temporarily disable `Geoffrey Frogeye's trackers list`

### PR DESCRIPTION
**Pull request by IceCodeNew**
For `hostfiles.frogeye.fr` has been offline for hours.

Refer:
a. https://port.ping.pe/hostfiles.frogeye.fr:443
b. https://i.ping.pe/h/M/img_hMz19G0Y.png

### CODE REVIEW

**Comment by jedisct1** [comment]
Looks like it's back :)

**Comment by IceCodeNew** [comment]
I suggest we add a To-do for `generate-domains-blocklist.py` is not dealing with network error well.
While generating a blocklist, any source which has failed to fetch could lead to an empty list. Such a result is not acceptable for me.

**Comment by jedisct1** [comment]
If you need to use the output immediately, the common way to do it is to use a temporary file, that gets renamed on success:

```sh
generate-domains-blocklist.py -o list.tmp && mv -f list.tmp list.txt
```

This also ensures that the file is always completely written.

**Comment by IceCodeNew** [comment]
> If you need to use the output immediately, the common way to do it is to use a temporary file, that gets renamed on success:
> 
> ```shell
> generate-domains-blocklist.py -o list.tmp && mv -f list.tmp list.txt
> ```
> 
> This also ensures that the file is always completely written.

You are right. I definitely need to clean up some old codes.
This problem could be fixed on my side.

**Comment by IceCodeNew** [comment]
@jedisct1 `hostfiles.frogeye.fr` is offline again :-(

**Pull request closed without merging**
