### PR TITLE
Adding the ability to do TLS client authentication for DoH

### PR DESCRIPTION
**Pull request by kev-null**
Following on from issue [1156](https://github.com/DNSCrypt/dnscrypt-proxy/issues/1156), this PR adds the ability to use TLS client authentication for DoH services.

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks!

Can you just resolve the little merge conflict, so we can merge it?

**Comment by kev-null** [comment]
Hey @jedisct1 - I resolved the merge conflict in commit [12d108ea83232b0654664f7d8676c7f5c2d3e217](https://github.com/DNSCrypt/dnscrypt-proxy/pull/1203/commits/12d108ea83232b0654664f7d8676c7f5c2d3e217), 2nd commit in this PR.

I can't see any other conflicts here?

**Comment by jedisct1** [comment]
Weird, GitHub is telling me that merging is impossible due to conflicts? The "Rebase and merge" button if grayed out.

**Comment by jedisct1** [comment]
Squash and merge, worked.

Thanks! :)

**Comment by chantra** [comment]
Thanks @jedisct1 and @kev-null !

**Comment by chantra** [comment]
cc @kei0 from #1156

**Pull request merged**
