### PR TITLE
Enhance logging

### PR DESCRIPTION
**Pull request by fholzer**
Enhance query logging by adding:
* Total request time
   The duration between dnscrypt-proxy receiving the request and it sending the response
* Upstream request time
   The duration between sending a request to an upstream DNS server and us receiving the response. Including requests forwarded based on `forwarding_rules`.

### CODE REVIEW

**Comment by jedisct1** [comment]
The duration is difficult to parse due to variable units. Can we get them all as a quantity of the same unit?

**Comment by fholzer** [comment]
Sure. Wasn't sure, if you want it human readable in the tsv, and machine readable in ltsv...
Is nanoseconds fine, or overkill. (That's what i used for ltsv)

**Comment by jedisct1** [comment]
Milliseconds are probably granular enough :)

**Comment by jedisct1** [comment]
Thanks!

Do we need both values?

I've been running this a bit, with and without forwarding, and the numbers are always really close.

When would they substantially differ?

**Comment by fholzer** [comment]
>I've been running this a bit, with and without forwarding, and the numbers are always really close.
>When would they substantially differ?
Point taken. When using a unit smaller than milliseconds you'd see a difference. Yes they should be really close all the time. If they wouldn't be, then that would point to some issue with dnscrypt-proxy I suppose. So it might come in handy for debugging issues, but not for regular use, true.

You want me to remove one of the two? If so, which one?

On another note, I was thinking about adding an additional field to the query log that reflects whether the response was served from cache or not. Would you be interested in that? (Maybe only in ltsv?)
Something like `cachehit:true`/`cachehit:false`.

**Comment by fholzer** [comment]
Also: thank you for maintaining this project!

**Comment by jedisct1** [comment]
Maybe keep only the total time, especially since the code path is simpler?

Having a `cachehit` property (maybe just `hit`?) in the LTSV file can indeed be interesting.

**Pull request merged**
