### PR TITLE
Update the minisig file timestamp together with the source file

### PR DESCRIPTION
**Pull request by lifenjoiner**

### CODE REVIEW

**Comment by jedisct1** [comment]
Sorry, I don't understand that code at all.

What does `writeToCache()` do? How is it different from `writeSource()`? Why do timestamps have to be manually changed?

I'm completely lost.

**Comment by lifenjoiner** [comment]
Whaaat? ChatGPT?
If `bytes.Equal(source.in, bin)`, the files won't be touched. And, `fetchWithCache` requires the timestamp of the source file.

**Comment by lifenjoiner** [comment]
Seems it has been patched.

**Comment by jedisct1** [comment]
I didn't remember we were doing such a thing. Cool.

The whole way we handle sources is weird, though. Looks like we are keeping a copy of the markdown files in memory to parse them later. I don't get why the files are not parsed at the same time as they are read.

**Pull request closed without merging**
