### PR TITLE
Watch plugin config files, automatic reload plugin on a file update

### PR DESCRIPTION
**Pull request by jrnewell**
Made an attempt to add the requested feature outlined in this issue (https://github.com/jedisct1/dnscrypt-proxy/issues/714)

- Watch config files (`'forwarding-rules.txt' 'cloaking-rules.txt', ...`) of enabled plugins using https://github.com/fsnotify/fsnotify.  If the config files are updated, the plugin is rebuilt in the background and once initialized replaces the old plugin.
- If the plugin has a logger (i.e. `ip-block`), the logger is migrated to the new plugin instance
- Add a 2 second debounce, so if many updates occur simultaneously (and to handle the issue where MacOS can get dual update notifications from SpotLight), the plugin will be recreated only once
- Add a config option `hot_reload_plugins` to enable this feature (off by default).

Let me know what you think.  Go is not my primary language :)

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by publicarray** [comment]
Ping @jedisct1 

@jrnewell I think this is a great idea!

**Comment by jedisct1** [comment]
This is an excellent idea, and the proposed changes are excellent. And thanks for thinking about the debounce feature!

Reloading the configuration was originally planned using the `Reload()` trait that all plugins have to implement already. I have some early code using this, and after seeing your PR, my plan was so do a mix of both approaches. But I still have to find some time to do it.

**Comment by unixfox** [comment]
why closing this PR? this feature would be awesome when managing a dynamic blacklist with DNSCrypt-proxy

**Comment by jedisct1** [comment]
That feature will be implemented differently.

**Pull request closed without merging**
