### PR TITLE
Upgrade quic-go to v0.36.1

### PR DESCRIPTION
**Pull request by lifenjoiner**
quic-go has made breaking changes since v0.35.0, includes implementing `CloseIdleConnections`.
Now, the local listener UDPConn are reused, and don't pile up. But, 1 instance (IPv4/IPv6) persists for each connected server.

The latency seems at the same level:
quic-go-0.36.1-qc

### CODE REVIEW

**Comment by lifenjoiner** [comment]
By tracing back, the UDPConn piling up issue was solved in upstream by closing the staled UDPConn:
[implement http3.RoundTripper.CloseIdleConnections](https://github.com/quic-go/quic-go/commit/cec79d338c645522923c92ffc88fee580c711315?diff=split#diff-1a39802c78436aea40cfc4347fd19f4defb7a59ba68b0383427c1d31ece5583eR214) (v0.35.0)

**Comment by jedisct1** [comment]
Thank you!

**Comment by lifenjoiner** [comment]
https://github.com/quic-go/quic-go/pull/3943 is expected to reduce the `NETWORK_ERROR` ratio, and lower the `RTT` of those servers,  thus increase the availability.

**Comment by jedisct1** [comment]
Nice!

**Pull request merged**
