### PR TITLE
Pull980fix

### PR DESCRIPTION
**Pull request by vbauerster**
follow up on [comment](https://github.com/DNSCrypt/dnscrypt-proxy/pull/980#issuecomment-548153169).

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you!

**Comment by vbauerster** [comment]
No prob, thank you for review!

**Comment by jedisct1** [comment]
Oops, not good.

It doesn't start any more on BSD.

```sh
$ ./dnscrypt-proxy
[2019-10-31 16:58:29] [DEBUG] No service system detected.
[2019-10-31 16:58:29] [NOTICE] Stopped.
```

**Comment by jedisct1** [comment]
Seems to be broken on Android as well.

**Comment by jedisct1** [comment]
`app.Start(nil)` is called, but is not blocking, so the app immediately ends.

**Comment by jedisct1** [comment]
Replacing `app.Start(nil)` with `app.appMain()` make the application usable, but it now requires two signals to quit it :/

**Comment by vbauerster** [comment]
I have a quick fix, wait!

**Comment by vbauerster** [comment]
I hope following patch should fix this, but not sure if I should add commit to this PR or make a new one.
[](https://postimg.cc/LYPKWwMB)

I suppose `pidfile` is created for android and bsd, so calling `app.Stop(nil)` in any case.

**Comment by jedisct1** [comment]
Version 2.0.29-beta.3 was pretty stable, so I tagged a new version that's essentially 2.0.29-beta.3. 

Merging too many changes between the beta and the final version wasn't a good idea at all, my bad :(

Now that 2.0.31 should be a stable version that supports anonymization, we can relax and take a bit more time to test tricky changes like this :)

**Comment by vbauerster** [comment]
ok, let me know if you still interested in this PR.

**Pull request merged**
