### PR TITLE
Drop privileges with exec

### PR DESCRIPTION
**Pull request by publicarray**
@jedisct1 What do you think? I know its a bit messy, but I like to get some feedback first. I'm using your method from #441 

From the issue I take it that would have preferred this to be implemented in `kardianos/service` with an API instead?

### CODE REVIEW

**Comment by publicarray** [comment]
Please don't merge as this does not work on Windows

**Comment by jedisct1** [comment]
Still, this is fantastic, thanks a lot!

Having this implemented in `kardianos/service` (or equivalent) would have been neat to avoid reimplementing the same thing in every single application. But having this already fixed in dnscrypt-proxy is already awesome.

Wondering how this affects logging, though. We probably need to do the descriptor passing thing with logfiles descriptors, too.

**Comment by publicarray** [comment]
Yea totally missed the log file descriptor. How would you feel with something like this?

```go
if !proxy.child {
	fds = append(fds, dlog.GetFileDescriptor())
} else {
	dlog.SetFileDescriptor(os.NewFile(uintptr(3), "logFile"))
}
```

I took a quick look at kardianos/service. I think because the package is just just concerned with creating services I can't help thinking of the gnu model (do one thing only but do it well). It might be better to create a brand new package just for dropping the privilege with exec. Basically I'm not confident enough to do it in  kardianos/service.

**Comment by publicarray** [comment]
Unfortunately I have no idea what to do with the logging plugins

**Comment by jedisct1** [comment]
Log files need to be owned by the proxy user, since they are automatically rotated. So, I don't think anything has to be done.

**Comment by publicarray** [comment]
Ah that makes sense. I was over thinking it.

**Pull request merged**
